### ISSUE TITLE
ERROR in ./contract/MyToken.sol

### ISSUE THREAD

**Issue by glowkeeper** [uzyn/ethereum-webpack-example-dapp#8]
Just trying to get this working, but I get an error trying to run `npm start`:

```
[543] ./dapp/js/component/Web3.jsx 1.65 kB {0} [built] [1 error]
  [545] ./dapp/js/component/MyToken.jsx 1.65 kB {0} [built]

ERROR in ./contract/MyToken.sol
Module build failed: Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/web3/lib/web3/contract.js:147:46)
    at /Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/web3/lib/web3/method.js:142:25
    at /Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/steve/gitrepos/LFC/src/react-ethereum-dapp-template/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./dapp/js/component/Web3.jsx 12:15-55
webpack: bundle is now VALID.
```

Node v6.8.1
npm 3.10.8

Any ideas?

**Comment by uzyn** [comment]
What Ethereum client are you using? And if Geth/Parity, are you on live or testnet?

**Comment by bsisic** [comment]
same error w Geth on testnet

**Comment by glowkeeper** [comment]
+1 @bsisic42, geth on a private testnet.

**Comment by jln1989** [comment]
+1 same error on testrpc

**Comment by re2005** [comment]
U just need to pass gas param somewhere a bit higher than the default been used. where can we edit that?

Using Truffle I've fixed by adding 'gas' amount

module.exports = {
    networks: {
        development: {
            host: 'localhost',
            port: 8545,
            network_id: '*',
            from: '',
            gas: 4712388,
        },
    },
};
